In [1]:
import numpy as np

In [3]:
joao_pts= [20, 30, 40, 15]
pedro_pts = [100, 24, 48, 23]
maria_pts = [92, 22, 34, 12]
marcos_pts = [12, 34, 12, 43]

pontos = np.array([joao_pts, pedro_pts, maria_pts, marcos_pts])

In [4]:
pontos

array([[ 20,  30,  40,  15],
       [100,  24,  48,  23],
       [ 92,  22,  34,  12],
       [ 12,  34,  12,  43]])

In [5]:
pontos[0]

array([20, 30, 40, 15])

In [9]:
pontos[1,0]

100

In [7]:
my_data = np.arange(0,20)
print(my_data)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [8]:
mat1 = np.reshape(my_data, (5,4)) # Transforma my_data em uma matriz 5 x 4
mat1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [10]:
pontos.item(5)

24